task: arc_challenge_local
dataset_path: json
dataset_kwargs:
  data_files:
    test: /data/home/yuanxiaosong/.cache/huggingface/datasets/arc_local/arc_challenge_test.jsonl
output_type: multiple_choice
test_split: test
doc_to_text: "Question: {{question}}\nAnswer:"
doc_to_target: "{{choices.label.index(answerKey)}}"
doc_to_choice: "{{choices.text}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
