dataset_kwargs:
  data_files:
    validation: /data/home/yuanxiaosong/GAQ-Aware-Prune/data/zeroshot/hellaswag/validation.jsonl
dataset_path: json
doc_to_choice: '{{endings}}'
doc_to_target: '{{label}}'
doc_to_text: '{{ctx}}'
metric_list:
- aggregation: mean
  higher_is_better: true
  metric: acc
- aggregation: mean
  higher_is_better: true
  metric: acc_norm
output_type: multiple_choice
task: hellaswag_local
validation_split: validation
