dataset_kwargs:
  data_files:
    validation: /data/home/yuanxiaosong/GAQ-Aware-Prune/data/zeroshot/openbookqa/validation.jsonl
dataset_path: json
doc_to_choice: '{{choices.text}}'
doc_to_target: '{{choices.label.index(answerKey)}}'
doc_to_text: '{{question_stem}}'
metric_list:
- aggregation: mean
  higher_is_better: true
  metric: acc
- aggregation: mean
  higher_is_better: true
  metric: acc_norm
output_type: multiple_choice
task: openbookqa_local
validation_split: validation
